apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  TOKEN_EXPIRE: "2562000"
  NODE_ENV: "development"
  PORT: "3001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev
data:
  REACT_APP_API_URL: "https://dev.ecomp.codes"
  # PORT removed — nginx uses 80 by default