apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
type: Opaque
stringData:
  EMAIL_USER: reactstream0@gmail.com
  EMAIL_PASS: cyyu kzly monr ywrs
  MONGO_URI: mongodb://mongo:27017/ecommerce-dev
  JWT_SECRET: jwtSecret
