# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/intrepid-alloy-493208-k9/backend:v1
          ports:
            - containerPort: 3003
          envFrom:
          - secretRef:
              name: backend-secret
          - configMapRef:
              name: backend-config
---
# Service (ClusterIP — internal only) ───────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
spec:
  
  selector:
    app: backend
  ports:
    - port: 3003
      targetPort: 3003
