apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: prod.ecomp.codes
    http:
      paths:
      - path: /api        # ← API traffic goes to backend
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3003
      - path: /           # ← everything else goes to frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80