# Secret for Backend Deployment in Production Environment

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  EMAIL_USER: reactstream0@gmail.com
  EMAIL_PASS: cyyu kzly monr ywrs
  MONGO_URI: mongodb://admin:password123@mongo:27017/ecommerce?authSource=admin
  JWT_SECRET: jwtSecret


